abstract: Create PAR distributions from PPDs
author: Steffen Mueller (smueller@cpan.org)
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: PAR-Dist-FromPPD
no_index: 
  directory: 
    - inc
    - t
requires: 
  Archive::Tar: 0
  Cwd: 0
  File::Copy: 0
  File::Path: 0
  File::Spec: 0
  File::Temp: 0
  Getopt::Long: 0
  LWP::Simple: 0
  PAR::Dist: 0.20
  XML::Parser: 0
  perl: 5.6.0
version: 0.02
